### ISSUE TITLE
certificate folder

### ISSUE THREAD

**Issue by DevrG03** [MR-DHRUV/Automate_certificate_generation_and_mailing#1]
It should be mentioned to users to create a **certificates folder**, or should be automatically created while running the script else:

`Error: ENOENT: no such file or directory, open '/Users/user/Desktop/Automate_certificate_generation_and_mailing/certificates/cert_participant.pdf'
    at Object.openSync (node:fs:595:3)
    at Object.writeFileSync (node:fs:2216:35)
    at genCert (/Users/devrajsinhgohil/Desktop/Automate_certificate_generation_and_mailing/genCert.js:41:14)
    at async /Users/devrajsinhgohil/Desktop/Automate_certificate_generation_and_mailing/index.js:23:17 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/user/Desktop/Automate_certificate_generation_and_mailing/certificates/cert_participant.pdf'`

the above shown error pops up

**Comment by MR-DHRUV** [comment]
Yes. thanks for informing I have fixed it.
