### ISSUE TITLE
Sender name

### ISSUE THREAD

**Issue by DevrG03** [MR-DHRUV/Automate_certificate_generation_and_mailing#2]
Eventhough the email is mine the name shown to the receiver is Dhruv Gupta

<img width="1440" alt="Screenshot 2023-03-18 at 7 40 46 PM" src="https://user-images.githubusercontent.com/103804567/226111287-7a457523-f46c-4904-a83b-ec9639ea195f.png">

**Comment by MR-DHRUV** [comment]
I have fixed the issue please take a pull from main branch and you can also navigate to file authifyMailer.js and at line no 20 write your name.
